name: Create GitHub Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: changelog
      uses: actions/github-script@v6.4.0
      env:
        COMMITS: ${{ toJSON(github.event.commits) }}
      with:
        result-encoding: string
        script: |
          const commits = JSON.parse(process.env.COMMITS);
          var lines = "## What’s Changed\n\n";
          for (const commit of commits) {
          lines += "- " + commit.message + " (" + commit.id + ") @" + commit.author.username + "\n"
          }
          return lines

    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.changelog.outputs.result }}
        draft: false
        prerelease: false

  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml

